spring:
  profiles:
    active: dev
  application:
    name: boot1
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/boot?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: boot
    password: boot
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev #, faker
  jpa:
    show-sql: true
  server:
    port: 8080
